import Head from 'next/head'

export function Headertitle()
{
    return (
        <Head>
            <title>清水達也選手後援会ホームページ</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/shimizu-kouenkai.ico" />
        </Head> 
    )
}
    